=== Matty2603/webdesign/kundenliste.dtd
<!ELEMENT kundenliste (kunde+)>
  <!ELEMENT kunde (vorname, nachname, alter, adresse)>
  <!ELEMENT vorname (#PCDATA)>
  <!ELEMENT nachname (#PCDATA)>
  <!ELEMENT alter (#PCDATA)>
  <!ELEMENT adresse (strasse, postleitzahl, ort, bundesland)>
  <!ELEMENT strasse (#PCDATA)>
  <!ELEMENT postleitzahl (#PCDATA)>
  <!ELEMENT ort (#PCDATA)>
  <!ELEMENT bundesland (#PCDATA)>

  <!ATTLIST kunde
    kundenart (Kunde|Neukunde|Stammkunde) #REQUIRED
    geschlecht (Frau|Mann|Inter) #REQUIRED> <!-- IMPLIED FIXED-->
  <!ATTLIST adresse adressart (Privatadresse|GeschÃ¤ftsadresse|Rechnungsadresse|Lieferadresse) #REQUIRED><!--IMPLIED FIXED-->

=== Matty2603/webdesign/einstiegExtern.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE kundenliste SYSTEM "I:\beProductive\webDesign\xml\kundenliste.dtd">
<kundenliste>
  <kunde kundenart="Kunde" geschlecht="Frau">
    <vorname>string</vorname>
    <nachname>string</nachname>
    <alter>string</alter>
    <adresse adressart="Privatadresse">
      <strasse>string</strasse>
      <postleitzahl>string</postleitzahl>
      <ort>string</ort>
      <bundesland>string</bundesland>
    </adresse>
  </kunde>
</kundenliste>
